# docker/docker-compose.yml
services:
  ollama:
  profiles: ["cpu"]
    build:
      context: ./ollamaimage
      dockerfile: Dockerfile
    container_name: ollamaserver
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=llama3.2:3b
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 20s
      retries: 50

  app_cpu:
    profiles: ["cpu"]
    build:
      context: ..             
      dockerfile: ./docker/Dockerfile
    container_name: at-mind-app
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"
    restart: unless-stopped
    
  vLLM:
    profiles: ["gpu"]
    build:
      context: ..
      dockerfile: docker/vllm/Dockerfile #STILL NEED TO CREATE THIS DOCKERFILE
    ports:
      - "8000:8000"
    device_requests:
      - driver: nvidia
        count: all
        capabilities: ["gpu"]


  app_gpu:
    profiles: ["gpu"]
    build:
      context: ..             
      dockerfile: ./at_mind/fastapi/Dockerfile #STILL NEED TO CREATE THIS DOCKERFILE
    container_name: at-mind-app
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  ollama_models:


